### DISCUSSION TITLE
Is it possible to "align" the X axes of the various graphs?

### DISCUSSION THREAD

**Discussion by jfly** [ClementTsang/bottom#1292] [Q&A]
Note how the default layout has 3 time-based graphs in it, and their X axes do not align with each other:

![image](https://github.com/ClementTsang/bottom/assets/277474/2ff12f21-53cd-485e-8d2e-cd08499c65c9)

I tried playing around with a custom layout to accomplish this, but it appears that if I create a layout element of type "cpu", it still includes the legend, which makes it hard/impossible to line up the graphs. For example, with this config file:

```toml
$ cat ~/tmp/btm.toml
[[row]]
  ratio=1
  [[row.child]]
  type="cpu"
[[row]]
  ratio=1
  [[row.child]]
    ratio=11
    type="mem"
[[row]]
  ratio=1
  [[row.child]]
    type="net"
```

I get this result when running `btm --config ~/tmp/btm.toml`:

![image](https://github.com/ClementTsang/bottom/assets/277474/5e008619-0240-4169-90e2-a81d0e5608ce)

Note how the Memory and Network widgets line up with each other, but the CPU one does not. This makes it difficult to correlate changes across the various widgets.
