### DISCUSSION TITLE
How can I use memb in a process table instead of mem%?

### DISCUSSION THREAD

**Discussion by mock1328** [ClementTsang/bottom#1604] [Q&A] [answered]
I didn't found any notes about it in either default config file, on issues or on website

**Comment by mock1328** [comment, marked as answer]
Whoops, found it in config:

```toml
[flags]
process_memory_as_value = true
```
