### ISSUE TITLE
Migrate some documentation to wiki and/or manpages

### ISSUE THREAD

**Issue by ClementTsang** [ClementTsang/bottom#383]
The massive README is probably not very pleasant.

Also move CONTRIBUTING and add more details to building for dev use.

**Comment by polarathene** [comment]
You might like to use something like [mkdocs-material](https://squidfunk.github.io/mkdocs-material/)?

You can split the README docs into smaller markdown files and it's a little nicer than dealing with Github wiki feature which you can't keep in sync with the project repo (eg pull requests where some docs would be part of the contribution, you also can't as easily track doc history with relevant git repo history of the project).

Earlier in the year I migrated the Github Wiki docs for [`docker-mailserver`](https://github.com/docker-mailserver/docker-mailserver) to use `mkdocs-material`, Github Actions build and deploy to Github Pages when the primary branch has a relevant push event.

More recently I contributed the pull request preview feature, but I don't think this project would need or benefit from that as much.

---

You can probably skip the versioned docs feature to keep it simpler, [here is the deploy workflow I mentioned](https://github.com/docker-mailserver/docker-mailserver/blob/master/.github/workflows/docs-production-deploy.yml), you should be fine with:

```yaml
name: 'Documentation'

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy-docs.yml'
      - 'docs/**'

env:
  # Assign commit authorship to official Github Actions bot when pushing to the `gh-pages` branch:
  GIT_USER: 'github-actions[bot]'
  GIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'

jobs:
  deploy:
    name: 'Deploy Docs'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - name: 'Build with mkdocs-material via Docker'
        working-directory: docs
        run: docker run --rm -v "${PWD}:/docs" squidfunk/mkdocs-material:latest build --strict

      - name: 'Deploy to Github Pages'
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build directory contents to publish to the `gh-pages` branch:
          publish_dir: ./docs/site
          # Directory to place `publish_dir` contents on the `gh-pages` branch:
          destination_dir: ${{ env.DOCS_VERSION }}
          user_name: ${{ env.GIT_USER }}
          user_email: ${{ env.GIT_EMAIL }}
```

You then have a `docs` directory in your project, with [contents like this](https://github.com/docker-mailserver/docker-mailserver/tree/master/docs). The `docs/content/assets` and `docs/overrides` directories can be ignored.

The `docs/content` is for your markdown files with a main page as `index.md`. As your docs don't need the grouping and hierarchy you can just have a few `.md` files in there named however you like.

Config for the docs are managed with [`mkdocs.yml`](https://github.com/docker-mailserver/docker-mailserver/blob/master/docs/mkdocs.yml), the comments and official docs for `mkdocs-material` explain all of that fairly well. Yours might look like:

```yaml
# Site specific:
site_name: bottom
site_description: Yet another cross-platform graphical process/system monitor.
site_author: Clement Tsang

# Project source specific:
repo_name: 'bottom'
repo_url: 'https://github.com/ClementTsang/bottom'
edit_uri: 'edit/master/docs/content'
docs_dir: 'content/'
site_url: 'https://ClementTsang.github.io/bottom/'

# Anything related to the `mkdocs-material` theme config goes here:
theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.instant

# Various extensions for `mkdocs` are enabled and configured here to extend supported markdown syntax/features.
markdown_extensions:
  - toc:
      anchorlink: true
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight

# Hard-coded navigation list. Key(UI label): Value(relative filepath from `docs_dir`).
# - If referencing a file more than once, the URLs will all point to the nav hierarchy of the last file reference entry. That usually breaks UX, try avoid it.
# - The top-level elements are presented as tabs (due to `theme.features.navigation.tabs`).
#   - Nested elements appear in the sidebar (left) of each tabs page.
#   - 3rd level and beyond are automatically expanded in the sidebar instead of collapsed (due to `theme.features.navigation.expand`)
nav:
  - 'Home': index.md
  - 'Support': support.md
  - 'Installation': installation.md
  - 'Usage': usage.md
  - 'Features': features.md
  - 'FAQ': faq.md
  - 'Configuration':
    - 'Config flags': config/flags.md
    - 'Theming': config/theming.md
    - 'Layout': config/layout.md
    - 'Disk, temperature, and network filtering': config/filtering.md
```

That should give a rough idea that you can experiment with :)

The navigation labels and order is all managed in that `nav` section of the config, how it's presented on the page can be configured under `theme.features`, just remove any that don't seem necessary or experiment until you find what you prefer best for your docs.

`markdown_extensions` section is just enabling some features, you don't necessary need all those and can remove them, or leave them as is, the docs are generated through a build process, they're just extending the markdown parser support.

Before pushing all that into git and onto Github, you can test/view the docs locally with this docker command:

```bash
docker run --rm -it --user "$(id -u):$(id -g)" -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material:latest
```

The default command is the dev server, so as you make changes to local files it should reflect those automatically, otherwise just restart the container.

If you're unfamiliar with docker, the `--user` flag is to run the container with your UID and GID (_assuming a linux host_) which will be used when writing any data to the local volume bind mount (`-v`), which is the directory you run the command from (it should be the docs folder).

Then just visit `localhost:8000` in the browser to view your docs! :grinning:

To keep it simple when starting out, have the single `index.md` nav entry in your `mkdocs.yml` as your current `README.md`, place the `assets` directory with your screenshot images into `docs/content/assets` (_`docs/content/` will roughly match `localhost:8000/`. When an actual build is made, the contents is copied over to a build output folder instead_).

---

It's a fairly common / popular choice for hosting docs, you might have seen used with other plenty of other open-source projects :)
