### ISSUE TITLE
Battery display does not follow hide_table_gap configuration

### ISSUE THREAD

**Issue by cooper-anderson** [ClementTsang/bottom#385]
## Describe the bug

When setting the `hide_table_gap` setting to `true`, all tables correctly hides their gaps except for the `battery` table.

![image](https://user-images.githubusercontent.com/21961037/103720645-ae15bb00-4f80-11eb-90e3-0a6cbbe01b0f.png)

## To reproduce

1. Use a clear config file by way of `--config=/dev/null`
2. Enable flags `--battery` and `--hide_table_gap`
3. Observe both those flags working on their own, but not together.
> See top right of screenshot.

## bottom version

Running `bottom 0.5.6` on latest commit at the time of writing https://github.com/ClementTsang/bottom/commit/429978d1aa4bf4e77d098523baa6d5368b89d2e5

## bottom config file (if used)

```toml
[flags]
battery = true
default_time_value = 30000
disable_click = true
group_processes = true
hide_table_gap = true
left_legend = true
rate = 500
regex = true
show_table_scroll_position = true
```

## Installation method

Cloned with git and then built manually.

### Operating system, OS version, and architecture

_Please specify your operating system, the version, and architecture, so I can try to replicate your environment as best as possible. Note that the officially supported platforms are:_

macOS (`x86_64`)

_If your platform is not listed, please be aware I do not officially support it and may be unable to fix this issue._

### Terminal (i.e. urxvt, kitty, etc.)

Alacritty

### Shell (i.e. zsh, bash, etc.)

fish

### Miscellaneous system info

_Not totally necessary, but if possible, include details like:_

_RAM size:_ 16BG

_SWAP size:_ N/A

_CPU and number of cores:_ 2.5 GHz Quad-Core Intel Core i7

### Rust version

rustc 1.49.0 (e1884a8e3 2020-12-29)

## Additional context

❤️
