### ISSUE TITLE
Exclude snap from Disk's to allow seeing the real disks

### ISSUE THREAD

**Issue by Darkyere** [ClementTsang/bottom#431]
### Describe the feature request

A startup flag to the command btm or similar that exlude all snap loop devices from the disk menu.

### Additional context/details

This is because i never see anything else than snap loop devices in Disk's list and would find it more interesting to see my actual HDD's and such

**Comment by ClementTsang** [comment]
Would using the [disk filter functionality](https://github.com/ClementTsang/bottom#disk-temperature-and-network-filtering) be enough for now?  Ideally it would be easier to configure in-app (another thing on the ever-growing backburner), but assuming the disk names are like `/dev/loop`, off the top of my  head, you could do:

```toml
[disk_filter]
is_list_ignored = true
list = ["/dev/loop.*"]
regex = true
```
or something like that.  I intend on adding a filter based on mounts in the future as well, if that's required.

**Comment by Darkyere** [comment]
I belive it would suffice.

I just cant figure out how to do that on a snap.

Any clue of how i should proceed?

**Comment by ClementTsang** [comment]
Could you send a screenshot of what your disk widget looks like?

**Comment by Darkyere** [comment]
This is how my widget looks like

![Ubuntu 20 04 1 bottom](https://user-images.githubusercontent.com/23291749/110295723-b70f2100-7ff1-11eb-844e-8ca8b1ee30d4.png)

**Comment by ClementTsang** [comment]
Yeah, I think something like:

```toml
[disk_filter]
is_list_ignored = true
list = ["/dev/loop.*"]
regex = true
```

inside the bottom.toml config file would work for your case.
