### ISSUE TITLE
Process widget sorting by key press bug (simple)

### ISSUE THREAD

**Issue by joeftiger** [ClementTsang/bottom#626]
## Describe the bug
When entering the process widget and trying to sort by name, it instead sorts by cpu usage.

It seems like the wrong key is binded to it. I tried searching for it for a pull request, but didn't find my way in the repository. 

## What operating system/architecture are you using?
Arch Linux x86_64

## What terminal are you using `bottom` on?
`alacritty` as well as the linux shell (no GUI).

## What version are you on?
0.6.4

## How did you install `bottom`?
With the official package manager: `pacman -S bottom`

## How can we reproduce this?
In a terminal do:
1. Open `bottom`
2. Press `e` to enter enlarge process widget.
3. Press `n` to sort by name (as hinted at by the TUI).
4. See it getting sorted by CPU instead.

## What is the actual behaviour?
The widget sorts processes by CPU usage.

## What is the expected behaviour?
The widget sorts processes by name.

**Comment by ClementTsang** [comment]
Hmm, I can't reproduce this.  Could you record this in some way?  It's working fine on my end, also on Arch, installed via the package manager.

**Comment by joeftiger** [comment]
Not sure how much sense it makes to record this as it is just showing that it orders by `CPU` instead of `Name`. 
Pressing `c` and `n` gives the same result for me, as if they are mapped to the same thing.

**Comment by ClementTsang** [comment]
The reason I wanted to ask was so I could see what the sorting result was, because right now you're asking me to debug an issue blindfolded.

If all you're telling me is that the sorting results are the exact same, then without any extra details, this doesn't sound broken to me.  Sorting by CPU does two sorts - it first sorts by name, then by CPU usage.  

Now, unless all your processes are using 0% CPU this probably isn't the explaination, but I can't help you any further right now without at least getting an image of what's wrong and being unable to reproduce it with the exact same OS and setup.

**Comment by joeftiger** [comment]
Expectation:
<img src="https://user-images.githubusercontent.com/33136533/146682117-da5d4ecb-13e5-490c-a30f-4eb225a1d3e7.png" alt="expectation" width="400"/>
Actual:
<img src="https://user-images.githubusercontent.com/33136533/146682201-ac446837-2782-44ae-9154-900e2d78bff9.png" alt="actual" width="400"/>

**Comment by joeftiger** [comment]
Pressing `n` doesn't sort by name for me. It sorts by `cpu` only.

**Comment by ClementTsang** [comment]
Weird - I'm typing this on Arch as well and all the keybinds work fine.  I can't think of what is wrong.

**Comment by joeftiger** [comment]
I have some changes in the config regarding the layout of the widgets, but that shouldn't affect it. 
I'll try removing the config for now and reinstall again to see.

**Comment by ClementTsang** [comment]
Just to be sure, you're not hitting `N`, right?  Case matters.

**Comment by joeftiger** [comment]
I am only pressing `n`, not `N`, yes.

**Comment by ClementTsang** [comment]
And yeah, the config shouldn't affect anything.

**Comment by joeftiger** [comment]
I can confirm it works flawlessly with the default config. So something in the config affects it.

**Comment by ClementTsang** [comment]
...interesting.  Could you send me your config?

**Comment by ClementTsang** [comment]
Never mind - I think I found it.  Did you have `process_command` enabled?  Seems like that's causing issues.

**Comment by joeftiger** [comment]
my `bottom.toml` config:
<details>
```toml
[flags]
dot_marker = true
rate = 1000
hide_table_gap = true
tree = true
show_table_scroll_position = true
process_command = true
network_use_binary_prefix = true
battery = true

[[row]]
  ratio=3
  [[row.child]]
    ratio=40
    type="cpu"
  [[row.child]]
    ratio=27
    type="battery"
[[row]]
  ratio=3
  [[row.child]]
    type="mem"
  [[row.child]]
    [[row.child.child]]
      type="temp"
    [[row.child.child]]
      type="disk"
[[row]]
  ratio=3
  [[row.child]]
    type="net"
  [[row.child]]
    type="proc"
    default=true

[temp_filter]
is_list_ignored = true
list = ["thinkpad", "coretemp: Core"]
```
</details>
